#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
#define PORTIO_ACMP0_NEG_PIN                          (11U)
#define PORTIO_ACMP0_NEG_PORT                         (gpioPortB)
#define PORTIO_ACMP0_NEG_LOC                          (_ACMP_INPUTSEL_NEGSEL_APORT3YCH27)

#define PORTIO_ACMP0_POS_PIN                          (12U)
#define PORTIO_ACMP0_POS_PORT                         (gpioPortB)
#define PORTIO_ACMP0_POS_LOC                          (_ACMP_INPUTSEL_POSSEL_APORT3XCH28)

#define BSP_ACMP0_NEG_INPUT                           (_ACMP_INPUTSEL_NEGSEL_APORT3YCH27)
#define BSP_ACMP0_POS_INPUT                           (_ACMP_INPUTSEL_POSSEL_APORT3XCH28)
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BUTTON]
#define BSP_BUTTON_PRESENT                            (1)

#define BSP_BUTTON0_PIN                               (6U)
#define BSP_BUTTON0_PORT                              (gpioPortF)

#define BSP_BUTTON1_PIN                               (7U)
#define BSP_BUTTON1_PORT                              (gpioPortF)

#define BSP_BUTTON_COUNT                              (2U)
#define BSP_BUTTON_INIT                               { { BSP_BUTTON0_PORT, BSP_BUTTON0_PIN }, { BSP_BUTTON1_PORT, BSP_BUTTON1_PIN } }
#define BSP_BUTTON_GPIO_DOUT                          (HAL_GPIO_DOUT_LOW)
#define BSP_BUTTON_GPIO_MODE                          (HAL_GPIO_MODE_INPUT)
// [BUTTON]$

// $[CMU]
// [CMU]$

// $[DCDC]
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
#define PORTIO_I2C0_SCL_PIN                           (11U)
#define PORTIO_I2C0_SCL_PORT                          (gpioPortC)
#define PORTIO_I2C0_SCL_LOC                           (15U)

#define PORTIO_I2C0_SDA_PIN                           (10U)
#define PORTIO_I2C0_SDA_PORT                          (gpioPortC)
#define PORTIO_I2C0_SDA_LOC                           (15U)

#define HAL_I2C0_ENABLE                               (1)

#define BSP_I2C0_SDA_PIN                              (10U)
#define BSP_I2C0_SDA_PORT                             (gpioPortC)
#define BSP_I2C0_SDA_LOC                              (15U)

#define BSP_I2C0_SCL_PIN                              (11U)
#define BSP_I2C0_SCL_PORT                             (gpioPortC)
#define BSP_I2C0_SCL_LOC                              (15U)

#define HAL_I2C0_INIT_ENABLE                          (1)
// [I2C0]$

// $[I2CSENSOR]
#define HAL_I2CSENSOR_ENABLE                          (1)

#define BSP_I2CSENSOR_ENABLE_PIN                      (9U)
#define BSP_I2CSENSOR_ENABLE_PORT                     (gpioPortD)

#define BSP_I2CSENSOR_PERIPHERAL                      (HAL_I2C_PORT_I2C0)
#define BSP_I2CSENSOR_SDA_PIN                         (10U)
#define BSP_I2CSENSOR_SDA_PORT                        (gpioPortC)
#define BSP_I2CSENSOR_SDA_LOC                         (15U)

#define BSP_I2CSENSOR_SCL_PIN                         (11U)
#define BSP_I2CSENSOR_SCL_PORT                        (gpioPortC)
#define BSP_I2CSENSOR_SCL_LOC                         (15U)

#define HAL_I2CSENSOR_INIT_ENABLE                     (1)
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
#define BSP_LED_PRESENT                               (1)

#define BSP_LED0_PIN                                  (4U)
#define BSP_LED0_PORT                                 (gpioPortF)

#define BSP_LED1_PIN                                  (5U)
#define BSP_LED1_PORT                                 (gpioPortF)

#define BSP_LED_POLARITY                              (1)
#define BSP_LED_COUNT                                 (2U)
#define BSP_LED_INIT                                  { { BSP_LED0_PORT, BSP_LED0_PIN }, { BSP_LED1_PORT, BSP_LED1_PIN } }
// [LED]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[MODEM]
// [MODEM]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[SERIAL]
#define BSP_SERIAL_APP_PORT                           (HAL_SERIAL_PORT_USART0)
#define BSP_SERIAL_APP_RX_PIN                         (1U)
#define BSP_SERIAL_APP_RX_PORT                        (gpioPortA)
#define BSP_SERIAL_APP_RX_LOC                         (0U)

#define BSP_SERIAL_APP_TX_PIN                         (0U)
#define BSP_SERIAL_APP_TX_PORT                        (gpioPortA)
#define BSP_SERIAL_APP_TX_LOC                         (0U)

#define HAL_SERIAL_APP_BAUD_RATE                      (115200UL)
#define HAL_SERIAL_APP_FLOW_CONTROL                   (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
#define HAL_SPIDISPLAY_ENABLE                         (1)

#define BSP_SPIDISPLAY_EXTCOMIN_PIN                   (13U)
#define BSP_SPIDISPLAY_EXTCOMIN_PORT                  (gpioPortD)

#define BSP_SPIDISPLAY_ENABLE_PIN                     (15U)
#define BSP_SPIDISPLAY_ENABLE_PORT                    (gpioPortD)

#define HAL_SPIDISPLAY_EXTCOMIN_CALLBACK               
#define BSP_SPIDISPLAY_USART                          (HAL_SPI_PORT_USART1)
#define BSP_SPIDISPLAY_DISPLAY                        (HAL_DISPLAY_SHARP_LS013B7DH03)
#define HAL_SPIDISPLAY_EXTMODE_EXTCOMIN               (1)
#define HAL_SPIDISPLAY_EXTMODE_SPI                    (0)
#define HAL_SPIDISPLAY_EXTCOMIN_USE_PRS               (0)
#define HAL_SPIDISPLAY_EXTCOMIN_USE_CALLBACK          (0)
#define BSP_SPIDISPLAY_CS_PIN                         (14U)
#define BSP_SPIDISPLAY_CS_PORT                        (gpioPortD)
#define BSP_SPIDISPLAY_CS_LOC                         (19U)

#define BSP_SPIDISPLAY_CLK_PIN                        (8U)
#define BSP_SPIDISPLAY_CLK_PORT                       (gpioPortC)
#define BSP_SPIDISPLAY_CLK_LOC                        (11U)

#define BSP_SPIDISPLAY_MOSI_PIN                       (6U)
#define BSP_SPIDISPLAY_MOSI_PORT                      (gpioPortC)
#define BSP_SPIDISPLAY_MOSI_LOC                       (11U)

#define HAL_SPIDISPLAY_FREQUENCY                      (1000000UL)
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_RX_PIN                          (1U)
#define PORTIO_USART0_RX_PORT                         (gpioPortA)
#define PORTIO_USART0_RX_LOC                          (0U)

#define PORTIO_USART0_TX_PIN                          (0U)
#define PORTIO_USART0_TX_PORT                         (gpioPortA)
#define PORTIO_USART0_TX_LOC                          (0U)

#define HAL_USART0_ENABLE                             (1)

#define BSP_USART0_RX_PIN                             (1U)
#define BSP_USART0_RX_PORT                            (gpioPortA)
#define BSP_USART0_RX_LOC                             (0U)

#define BSP_USART0_TX_PIN                             (0U)
#define BSP_USART0_TX_PORT                            (gpioPortA)
#define BSP_USART0_TX_LOC                             (0U)

#define HAL_USART0_BAUD_RATE                          (115200UL)
#define HAL_USART0_FLOW_CONTROL                       (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_CLK_PIN                         (8U)
#define PORTIO_USART1_CLK_PORT                        (gpioPortC)
#define PORTIO_USART1_CLK_LOC                         (11U)

#define PORTIO_USART1_CS_PIN                          (14U)
#define PORTIO_USART1_CS_PORT                         (gpioPortD)
#define PORTIO_USART1_CS_LOC                          (19U)

#define PORTIO_USART1_TX_PIN                          (6U)
#define PORTIO_USART1_TX_PORT                         (gpioPortC)
#define PORTIO_USART1_TX_LOC                          (11U)

#define HAL_USART1_ENABLE                             (1)

#define BSP_USART1_CS_PIN                             (14U)
#define BSP_USART1_CS_PORT                            (gpioPortD)
#define BSP_USART1_CS_LOC                             (19U)

#define BSP_USART1_CLK_PIN                            (8U)
#define BSP_USART1_CLK_PORT                           (gpioPortC)
#define BSP_USART1_CLK_LOC                            (11U)

#define BSP_USART1_MOSI_PIN                           (6U)
#define BSP_USART1_MOSI_PORT                          (gpioPortC)
#define BSP_USART1_MOSI_LOC                           (11U)

#define HAL_USART1_FREQUENCY                          (1000000UL)
// [USART1]$

// $[VCOM]
#define HAL_VCOM_ENABLE                               (1)

#define BSP_VCOM_ENABLE_PIN                           (5U)
#define BSP_VCOM_ENABLE_PORT                          (gpioPortA)

// [VCOM]$

// $[WDOG]
// [WDOG]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

